name: Deploy to Cloud Run
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Auth to GCP (Workload Identity Federation)
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/86804897789/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: lovable-vitana-vers1@appspot.gserviceaccount.com

      # 2) Ensure gcloud is installed in the runner
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 474.0.0"

      # 3) Deploy (use the SA that has ActAs on the runtime SA)
      - name: Deploy to Cloud Run
        run: |
          set -euo pipefail
          gcloud run deploy crewai-gcp \
            --image=europe-west1-docker.pkg.dev/lovable-vitana-vers1/app/crewai-gcp:alive \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --no-use-http2 \
            --service-account=lovable-vitana-vers1@appspot.gserviceaccount.com \
            --project=lovable-vitana-vers1

      # 4) Test dynamically-discovered URL
      - name: Smoke test
        run: |
          set -euo pipefail
          URL="$(gcloud run services describe crewai-gcp \
            --project=lovable-vitana-vers1 \
            --region=europe-west1 \
            --format='value(status.url)')"
          echo "Cloud Run URL: $URL"

          # Both should be HTTP 200 + JSON
          curl -fsS "$URL/alive"
          curl -fsS "$URL/"
