      - name: Smoke test
        run: |
          set -euo pipefail
          URL="$(gcloud run services describe crewai-gcp \
            --project=lovable-vitana-vers1 \
            --region=europe-west1 \
            --format='value(status.url)')"
          echo "Cloud Run URL: $URL"

          # Try root first (works on your service), then /alive, then /healthz
          (curl -fsS "/" || curl -fsS "/alive" || curl -fsS "/healthz")
