name: DevOps Status → Google Chat
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # Daily 08:00 UTC
  push:
    branches: ["main","feature/**","governance-agents-**"]
    paths: ["crew_template/**","agents/**","services/**","scripts/**",".github/workflows/**"]
  pull_request:
    paths: ["crew_template/**","agents/**","services/**","scripts/**"]

jobs:
  status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Run status collector
        env:
          DEVOPS_WEBHOOK: ${{ secrets.DEVOPS_WEBHOOK }}
          GCP_PROJECT:    ${{ secrets.GCP_PROJECT }}
          GCP_REGION:     ${{ secrets.GCP_REGION }}
          HEALTH_WARN_MS: "1500"
          HEALTH_CRIT_MS: "3000"
          EXPECTED_MISSING_SERVICES: "oasis-mcp"
          REMOVED_SERVICES: "vitana-chat-gateway"
        run: |
          python3 scripts/ci/collect-status.py
