name: Gate-Quick

on:
  push:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/86804897789/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: gha-deployer@lovable-vitana-vers1.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug WIF token
        run: |
          set -euo pipefail
          gcloud auth list
          tok=$(gcloud auth print-access-token)
          echo "access token length: ${#tok}"
          test ${#tok} -gt 100
