name: Gate-Quick

on:
  push:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for WIF
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Deploy & smoke test (example)
        run: |
          gcloud run deploy worker-core \
            --source . \
            --region us-central1 \
            --quiet
