      - name: Smoke test Cloud Run service
        shell: bash
        run: |
          set -euo pipefail
          SERVICE="${SERVICE:-crewai-gcp}"
          REGION="${REGION:-europe-west1}"
          PROJECT_ID="${PROJECT_ID:-lovable-vitana-vers1}"

          echo "Discovering URL for service=$SERVICE region=$REGION project=$PROJECT_ID"
          URL="$(gcloud run services describe "$SERVICE" \
            --project="$PROJECT_ID" \
            --region="$REGION" \
            --format='value(status.url)')"

          if [[ -z "$URL" ]]; then
            echo "Failed to resolve Cloud Run URL"; exit 1
          fi

          echo "Cloud Run URL: $URL"

          # Try root first (current image returns 200 here), then /alive, then /healthz
          (curl -fsS "$URL/"        | tee /tmp/health.txt) \
          || (curl -fsS "$URL/alive"  | tee /tmp/health.txt) \
          || (curl -fsS "$URL/healthz" | tee /tmp/health.txt)

          echo "Health payload:"
          cat /tmp/health.txt
