name: Gate-Quick

on:
  push:
    branches: [ main ]

jobs:
  gate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # keep this for one more run; remove later if you want
      - name: Debug WIF token
        run: |
          set -euo pipefail
          gcloud auth list
          tok=$(gcloud auth print-access-token)
          echo "access token length: ${#tok}"
          test ${#tok} -gt 100

      # TODO: build / deploy / smoke steps here
